In [31]:
import pandas as pd
passengers = pd.read_csv('./train.csv')
passengers.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [32]:
passengers.shape

(891, 12)

In [33]:
passengers.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [34]:
passengers['Sex'] = passengers['Sex'].map({'female':1, 'male':0})

In [35]:
passengers['Age'].fillna(value = passengers['Age'].mean(), inplace = True)

In [36]:
passengers.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
dummies = pd.get_dummies(passengers['Pclass'])
del passengers['Pclass']
passengers = pd.concat([passengers, dummies], axis = 1, join = 'inner')

In [44]:
passengers.rename(columns = {1:'FirstClass', 2:'SecondClass', 3:'EtcClass'}, inplace = True)

In [46]:
passengers.head()

PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   
3            4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5         0                           Allen, Mr. William Henry   

   Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    0  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    1  38.0      1      0          PC 17599  71.2833   C85        C   
2    1  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    1  35.0      1      0            113803  53.1000  C123        S   
4    0  35.0      0      0            373450   8.0500   NaN        S   

   FirstClass  SecondClass  EtcClass  
0           0            0         1  
1           1            0         0  
2           0            0         1  
3           1            0         0  
4           0            0         1

In [48]:
passengers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Name         891 non-null    object 
 3   Sex          891 non-null    int64  
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  FirstClass   891 non-null    uint8  
 12  SecondClass  891 non-null    uint8  
 13  EtcClass     891 non-null    uint8  
dtypes: float64(2), int64(5), object(4), uint8(3)
memory usage: 79.3+ KB


In [49]:
features = passengers[['Sex', 'Age', 'FirstClass', 'SecondClass']]
survival = passengers[['Survived']]

In [50]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features,
                                                                           survival)

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_features = scaler.fit_transform(train_features)
test_features = scaler.fit_transform(test_features)

In [52]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(train_features, train_labels)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [53]:
model.score(train_features, train_labels)

0.8053892215568862

In [54]:
model.score(test_features, test_labels)

0.7623318385650224

In [55]:
model.coef_

array([[ 1.28431375, -0.29122162,  0.85793237,  0.44561555]])

In [59]:
import numpy as np

Jack = np.array([0.0,20.0,0.0,0.0])
Rose = np.array([1.0,17.0,1.0,0.0])
ME = np.array([1.0,32.0,1.0,0.0])

sample_passengers = np.array([Jack, Rose, ME])

In [60]:
sample_passengers = scaler.transform(sample_passengers)

In [61]:
model.predict(sample_passengers)

array([0, 1, 1], dtype=int64)

In [62]:
model.predict_proba(sample_passengers)

array([[0.88874769, 0.11125231],
       [0.06589447, 0.93410553],
       [0.09170063, 0.90829937]])